[default]
DEBUG=false
SQLALCHEMY_TRACK_MODIFICATIONS=false
FLASK_ADMIN_SWATCH = 'cerulean'
EXTENSIONS=[
	'delivery.ext.db:init_app',
	'delivery.ext.auth:init_app',
	'delivery.ext.admin:init_app',
	'delivery.ext.migrate:init_app',
	'delivery.ext.cli:init_app',	
	'delivery.ext.site:init_app',
	'delivery.ext.hooks:init_app',
	'delivery.ext.toolbar:init_app',
]

[development]
DEBUG=true
SQLALCHEMY_DATABASE_URI='sqlite:///delivery.db'

DEBUG_TB_TEMPLATE_EDITOR_ENABLED=true
DEBUG_TB_PROFILER_ENABLED=true
DEBUG_TB_INTERCEPT_REDIRECTS=false

EXTENSIONS=[
	'dynaconf_merge'	
]

[production]